# Generated by Django 3.1.4 on 2020-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
