# Generated by Django 3.1.4 on 2021-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210103_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='method',
            field=models.CharField(blank=True, choices=[('UPS', 'UPS'), ('InPost', 'InPost')], max_length=6, null=True),
        ),
    ]
