# Generated by Django 3.1.4 on 2021-01-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shippingaddress_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='method',
        ),
    ]
