version: "3.9"
services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=floppshop
      - POSTGRES_USER=flopp
      - POSTGRES_PASSWORD=floppshopp123kmdsklsdf
    ports:
    - 5555:5555
    command:
      -p 5555
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    ports:
    - 8000:8000
    env_file:
      - ./backend/env.dev
    command:
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
    - ./backend:/usr/src/backend/
  
  frontend:
    build: ./frontend
    ports:
    - 3000:3000
    command:
      npm start
    environment: 
    - CHOKIDAR_USEPOLLING=true
    volumes:
    - /usr/src/frontend/node_modules
    - ./frontend:/usr/src/frontend/

volumes:
  postgres_data:


