version: "3.9"
services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=floppshop
      - POSTGRES_USER=flopp
      - POSTGRES_PASSWORD=floppshopp123kmdsklsdf
    ports:
    - 5555:5555
    command:
      -p 5555
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  backend:
    build: .
    ports:
    - 8000:8000
    env_file:
      - ./env.dev
    command:
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
    - media:/code/media/
    - static:/code/static/

volumes:
  postgres_data:
  static:
  media:

