# Generated by Django 3.1.4 on 2021-02-06 15:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210123_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount_price',
            new_name='old_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
