# Generated by Django 3.1.4 on 2021-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210206_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='itemimage',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
