# Generated by Django 3.1.4 on 2021-02-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210207_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
