# Generated by Django 3.1.4 on 2020-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='opis', max_length=500),
            preserve_default=False,
        ),
    ]
