# Generated by Django 3.1.4 on 2021-01-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210103_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiping_method',
            field=models.CharField(blank=True, choices=[('UPS', 'UPS'), ('InPost', 'InPost')], max_length=6, null=True),
        ),
    ]
