# Generated by Django 3.1.4 on 2021-01-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_shiping_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_method',
            new_name='shipping_method',
        ),
    ]
