# Generated by Django 3.1.4 on 2021-01-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210104_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.item'),
        ),
    ]
