# Generated by Django 3.1.4 on 2021-01-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210104_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_method',
            new_name='method',
        ),
    ]
