# Generated by Django 3.1.4 on 2021-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210104_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
