# Generated by Django 3.1.4 on 2021-01-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_payuorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayUOrder',
            new_name='PayUNotification',
        ),
    ]
